import {Dimensions, StyleSheet, Platform} from 'react-native';
const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  mainContainer: {flex: 1},
  item: {
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * 0.01,
    marginVertical: height * 0.01,
  },
  checkBox: {
    width: Platform.OS == 'android' ? 30 : 15,
    height: Platform.OS == 'android' ? 30 : 15,
  },
  checkBoxText: {
    color: '#147AF3',
    fontWeight: '500',
    paddingHorizontal: width * 0.015,
    fontSize: width * 0.04,
  },
  innercont: {
    height: '100%',
    justifyContent: 'center',
  },
  title: {
    fontSize: 32,
  },
  Box: {
    borderRadius: width * 0.03,
    padding: width * 0.01,
    height: height * 0.475,
    backgroundColor: '#fff',
    paddingBottom: height * 0.02,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  Label: {
    fontWeight: '500',
    color: '#000',
    fontSize: width * 0.045,
    paddingVertical: height * 0.02,
    alignSelf: 'center',
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  BtnCont: {
    width: '90%',
    height: height * 0.06,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  LeftBtn: {
    width: '35%',
    height: '90%',
    borderWidth: 1,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  RightBtn: {
    width: '60%',
    height: '90%',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#147AF3',
  },
  pdf: {
    flex: 1,
    width: width,
    height: height,
  },
  PDFModalCont: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  PDFModalInner: {
    width: '100%',
    height: height * 0.8,
    borderRadius: width * 0.1,
    backgroundColor: 'white',
    justifyContent: 'center',
  },
  modalImage: {
    width: '70%',
    height: '70%',
  },
  pdfView: {
    height: '85%',
    width: width * 0.6,
  },
  pdfObj: {
    width: height * 0.5,
  },
  CrossImgCont: {
    width: width * 0.1,
    height: width * 0.1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: height * 0.01,
    right: width * 0.03,
    zIndex: 100,
  },
  innerContainer: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneText: {
    position: 'absolute',
    alignSelf: 'center',
    fontSize: width * 0.05,
    color: 'white',
    bottom: '10%',
    textDecorationLine: 'underline',
    color:'black'
  },
  videoView: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneText2: {
    position: 'absolute',
    alignSelf: 'center',
    color: '#fff',
    fontSize: width * 0.045,
    bottom: '5%',
    color:'black',
    textDecorationLine: 'underline',
  },
  documentStyling: {width: '100%', height: '100%'},
  feedbackButton: {
    width: width * 0.1,
    height: width * 0.125,
    position: 'absolute',
    zIndex: 99,
    left: width * 0.075,
  },
  ratingView: {
    width: width * 0.5,
    height: height * 0.6,
    marginLeft: width * 0.17,
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  ratingText: {
    fontWeight: "500",
    color: "#fff",
    fontSize: width * 0.055,
    textAlign: "center",
    paddingHorizontal: "15%",
  },
  ratingImage: {
    width: width * 0.3,
    height: width * 0.3,
    marginVertical: height * 0.03,
  },
  ratingFont: { fontWeight: "500", color:"black" },
  reviewText: {
    fontWeight: "bold",
    color: "#fff",
    minHeight: height * 0.07,
    fontSize: width * 0.04,
    textAlign: "center",
    width: width * 0.7,
  },
  reviewButton: {
    borderRadius: 10,
    backgroundColor: "#147AF3",
    padding: height * 0.01,
    width: width * 0.3,
    alignSelf: "center",
  },
  submitButton: {
    color: "#fff",
    fontSize: width * 0.04,
    textAlign: "center",
    width: "100%",
  },
  bottomText: {
    textAlign: 'center',
    color: '#fff',
    fontSize: width * 0.03,
  },
  bottomView: {
    alignItems: 'center',
    position: 'absolute',
    bottom: '2.5%',
  },
  safeView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  safeView2: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '90%',
    position: 'absolute',
    top: height * 0.08,
  },
  options: {
    width: width * 0.165,
    height: width * 0.165,
    backgroundColor: 'rgba(0,0,0,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: (width * 0.165) / 2,
  },
  optionsView: {paddingHorizontal: 20},
  optionsInnerView: {
    width: width * 0.15,
    height: width * 0.15,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: width * 0.15,
  },
  optionsImage: {
    width: '60%',
    height: '60%',
  },
  optionsTitle: {
    textAlign: 'center',
    color: '#fff',
    paddingTop: 5,
  },
  optionsInnerImage: {
    width: 12.5,
    height: 12.5,
    alignSelf: 'center',
    marginTop: 2.5,
  },
  mainView: {
    width: '80%',
  },
  experienceView: {
    fontWeight: '500',
    color: '#fff',
    fontSize: width * 0.055,
    paddingVertical: height * 0.02,
    alignSelf: 'center',
    textAlign: 'center',
  },
  outerView: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPress: {
    paddingVertical: height * 0.02,
    marginVertical: height * 0.015,
    marginHorizontal: height * 0.015,
    paddingHorizontal: width * 0.04,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 50,
  },
  imagePress: {
    width: 50,
    height: 50,
    tintColor: 'grey',
  },
  titleText: {
    fontSize: width * 0.04,
    textAlign: 'center',
    color: '#fff',
  },
  textView: {fontSize: width * 0.05, color: '#fff'},
  textImage: {
    width: width * 0.25,
    height: width * 0.25,
    marginVertical: height * 0.03,
  },
  viewPdf: {
    color: 'blue',
    textDecorationLine: 'underline',
    alignSelf: 'center',
    textAlign: 'center',
    paddingBottom: 10,
  },
  viewPdfIcon: {
    width: width * 0.2,
    height: width * 0.2,
    alignSelf: 'center',
  },
  warningText: {
    fontSize: width * 0.03,
    textAlign: 'center',
    color:'black',
  },
  pdfStyling: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  documentButton: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    height: height * 0.05,
    alignSelf: 'center',
    borderColor: '#147AF3',
    borderWidth: 1,
    backgroundColor: 'white',
  },
});
